# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Generatepass.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(302, 187)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.specifyCharecterNumberCheckBox = QtWidgets.QCheckBox(self.frame_4)
        self.specifyCharecterNumberCheckBox.setObjectName("specifyCharecterNumberCheckBox")
        self.horizontalLayout_2.addWidget(self.specifyCharecterNumberCheckBox)
        self.CharecterNumberLineEdit = QtWidgets.QLineEdit(self.frame_4)
        self.CharecterNumberLineEdit.setObjectName("CharecterNumberLineEdit")
        self.horizontalLayout_2.addWidget(self.CharecterNumberLineEdit)
        self.verticalLayout.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.upperCaseCheckbox = QtWidgets.QCheckBox(self.frame_5)
        self.upperCaseCheckbox.setObjectName("upperCaseCheckbox")
        self.horizontalLayout_3.addWidget(self.upperCaseCheckbox)
        self.lowerCaseCheckbox = QtWidgets.QCheckBox(self.frame_5)
        self.lowerCaseCheckbox.setObjectName("lowerCaseCheckbox")
        self.horizontalLayout_3.addWidget(self.lowerCaseCheckbox)
        self.numbersCheckbox = QtWidgets.QCheckBox(self.frame_5)
        self.numbersCheckbox.setObjectName("numbersCheckbox")
        self.horizontalLayout_3.addWidget(self.numbersCheckbox)
        self.verticalLayout.addWidget(self.frame_5)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.symbolsCheckbox = QtWidgets.QCheckBox(self.frame_3)
        self.symbolsCheckbox.setObjectName("symbolsCheckbox")
        self.horizontalLayout_4.addWidget(self.symbolsCheckbox)
        self.symbolsLineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.symbolsLineEdit.setObjectName("symbolsLineEdit")
        self.horizontalLayout_4.addWidget(self.symbolsLineEdit)
        self.verticalLayout.addWidget(self.frame_3)
        self.okButton = QtWidgets.QPushButton(self.frame)
        self.okButton.setObjectName("okButton")
        self.verticalLayout.addWidget(self.okButton)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "What Should the Password Contain?"))
        self.specifyCharecterNumberCheckBox.setText(_translate("Form", "Specify the number of charecters"))
        self.CharecterNumberLineEdit.setPlaceholderText(_translate("Form", "8"))
        self.upperCaseCheckbox.setText(_translate("Form", "Upper Case Charecters "))
        self.lowerCaseCheckbox.setText(_translate("Form", "Lower Case Charecters"))
        self.numbersCheckbox.setText(_translate("Form", "Numbers"))
        self.symbolsCheckbox.setText(_translate("Form", "Include Symbols"))
        self.symbolsLineEdit.setPlaceholderText(_translate("Form", "@#$%^&*..."))
        self.okButton.setText(_translate("Form", "Ok"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
