# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\ASUS\OneDrive\Desktop\FinalProjectX\ui_files\Url_input.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 50)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(500, 50))
        Form.setMaximumSize(QtCore.QSize(500, 50))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Url_label = QtWidgets.QLabel(Form)
        self.Url_label.setObjectName("Url_label")
        self.horizontalLayout_2.addWidget(self.Url_label)
        self.Url_user_input = QtWidgets.QLineEdit(Form)
        self.Url_user_input.setObjectName("Url_user_input")
        self.horizontalLayout_2.addWidget(self.Url_user_input)
        self.Url_button = QtWidgets.QPushButton(Form)
        self.Url_button.setObjectName("Url_button")
        self.horizontalLayout_2.addWidget(self.Url_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Url_label.setText(_translate("Form", "URL:"))
        self.Url_button.setText(_translate("Form", "Import file"))